target:
	javac LogHelper.java
	javac TcpServer.java
	javac UdpServer.java
	javac TcpClient.java
	javac UdpClient.java
	javac UtilTool.java

runtcpserver:
	java TcpServer 10000

runtcpclient:
	java TcpClient 108.179.159.240 10000

runudpserver:
	java UdpServer 10000

runudpclient:
	java UdpClient 108.179.159.240 10000